books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    path('',views.home,name="home"),
    path('debug/',views.debug,name="debug"),
    path('borrow/<int:book_id>',views.borrow,name="borrow"),
    path('sections/',views.sections,name="sections"),
    path('sections/sect/<int:dept>',views.sect,name="sect"),
    path('token/<int:book_id>',views.token,name='token')
    
]

main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static

from django.views.static import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('students/',include('students.urls')),
    path('',include("django.contrib.auth.urls")),
    
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]


if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.contrib.auth import views as v
from django.urls import path,include
from . import views

app_name = 'students'
urlpatterns = [
    # path('',include("django.contrib.auth.urls")),
    path('register',views.register,name='register'),
    path('login/',views.studentlogin,name="login"),
    path('student',views.student,name="student")
]

students/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Department(models.Model):
    name=models.CharField(max_length=200)
    icons=models.CharField(max_length=200)
    
    def __str__(self):
        return self.name

class Student(models.Model):
    # first_name=models.CharField(max_length=120)
    student_name=models.CharField(max_length=120)
    department=models.ForeignKey(Department,on_delete=models.CASCADE)
    student_id=models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.student_id} {self.department}"

students/forms.py
from django.contrib.auth import login,authenticate
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm, UsernameField 
from django.contrib.auth.models import User
from django import forms
from .models import Department

def getDepartmentsList():
    departments_obj = Department.objects.all()
    departments_list = list(departments_obj)
    depts = []
    for x in range(len(departments_list)):
        department = (x,str(departments_list[x]))
        depts.append(department)
    return depts
    
depts = getDepartmentsList()
# CHOICES = {
#       (1, 'Orange'),
#       (2, 'Mango'),
#       (3, 'Strawberries'),
#       (4, 'Grapes'),
      
# }

class RegistrationForm(UserCreationForm):
    username = forms.CharField(label="Student Resister ID",widget=forms.TextInput(attrs={'placeholder':'Student ID'}))
    email = forms.EmailField(label="Email",widget=forms.TextInput(attrs={'placeholder':'1901..@mcc.edu.in'}))
    department = forms.ChoiceField(choices = depts)
    class Meta():
        model = User
        fields = ["username","email","department","password1","password2"]

# class loginform(AuthenticationForm):
#         Studentid = UsernameField(widget=forms.TextInput(
#         attrs={'class': 'form-control', 'placeholder': 'Student ID', 'id': 'hello'}))
#         password = forms.CharField(widget=forms.PasswordInput(
#         attrs={
#             'class': 'form-control',
#             'placeholder': 'password',
#             'id': 'hi',
#         }))
        
# class UserLoginForm(AuthenticationForm):
#     def __init__(self, *args, **kwargs):
#         super(UserLoginForm, self).__init__(*args, **kwargs)

#     Studentid = UsernameField(widget=forms.TextInput(
#         attrs={'class': 'form-control', 'placeholder': 'Student ID', 'id': 'hello'}))
#     password = forms.CharField(widget=forms.PasswordInput(
#         attrs={
#             'class': 'form-control',
#             'placeholder': 'password',
#             'id': 'hi',
#         }
# ))

students/views.py
from django.shortcuts import render , redirect

from books.models import Book, Borrow
from .forms import RegistrationForm
from django.contrib.auth import authenticate,login
from .models import Department, Student
from django.contrib.auth.models import User



def getDepartmentsList(index):
    dept_query = Department.objects.all()
    dept_list = list(dept_query)
    depts = []
    for x in range(len(dept_list)):
        p = str(dept_list[x])
        depts.append(p)
    return depts[int(index)]

# Create your views here.
def studentlogin(request):
    if request.method == 'POST':
        username = request.POST.get('studentroll')
        password = request.POST['password']
        
        user = authenticate(username=username,password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
        return redirect("/")
    
    return render(request,'students/login.html' )


def logout(request):
    return render(request,'logged_out.html')

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username=request.POST.get('username')
            password= request.POST.get('password2')
            dept= request.POST.get('department')
            print(dept)
            dept_name = getDepartmentsList(dept)
            print(dept_name)
            
            # Querying Department Object
            department = Department.objects.get(name=dept_name)
            print(department)
            current_user = User.objects.get(username=username)
            print(current_user)
            #adding student
            new_student = Student(department=department,student_id=current_user)
            new_student.save()
            new_user = authenticate(username=username,
                                    password=password)
            login(request,new_user)
            return redirect("/")
    else:
        form = RegistrationForm()
        
    return render(request,'students/register.html',{'form': form})

def student(request):
    current_user = request.user
    student = Student.objects.get(student_id=current_user)
    borrwed = Borrow.objects.filter(student=student)
    context = {"user":current_user,"borrowed":borrwed}
    return render(request,'students/student.html', context)

students/templates/students/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- External cdn links -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="http://fonts.cdnfonts.com/css/sf-pro-display" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}{% endblock %}
    <style>
        *{
            font-family: 'SF Pro Display';
        }
    </style>
</head>
<body>
    
    <!-- navbar section -->
    <nav class="navbar navbar-expand-md bg-dark navbar-dark py-3 fixed-top">
        <div class="container">
            <a href="/" class="navbar-brand"> Miller Memorial Library </a>
            <button 
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navmenu"
            >
                <span class="navbar-toggler-icon"></span>
        </button>

            <div class="collapse navbar-collapse" id="navmenu"">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="/" class="nav-link">Home</a>
                    </li> 
                    <li class="nav-item">
                        <a href="{% url 'books:sections' %}" class="nav-link">Sections</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'students:student' %}" class="nav-link">{{user.username}}</a>
                    <li class="nav-item">
                        <a href="/logout" class="nav-link">logout</a>
                        {% else %}
                    </li><li class="nav-item">
                        <a href="/students/login" class="nav-link">{% block nav %} {% endblock %}</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>


    {% block content %}
    {% endblock %}

    <footer class="text-center text-lg-start" style="bottom:0%;">
      
        <!-- Copyright -->
        <div class="text-center pt-3 text-muted" style="font-size:13px;" >
          © 2020 Copyright
          <a class="text-muted" href="https://mcc.edu.in/" target="_blank" style="text-decoration: none;">Madras Christian College</a> <p>This is not a official site. Developed for Educational Purpose only. </p>
        </div>
        <!-- Copyright -->
      </footer>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
</body>
</html>

students/templates/students/login.html
{% extends 'students/base.html' %}
{% block title %} login {% endblock %}
{% block nav %}  {% endblock %}
{% block content %} 

{% load crispy_forms_tags %}
<section class=" flex-column d-flex align-items-center justify-content-center" style="height:90vh;">
    <div class="container">
        <div class="container col-sm-6 col-10 card py-3">
            <div class="fs-3">Login</div>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="">
                    <input class="form-control my-2" type="text" placeholder="Student ID" name="studentroll">
                </div>
                <div class="">
                    <input class="form-control my-2" type="password" placeholder="Password" name="password">
                </div>
                <button type="submit" class="btn btn-success">login</button>
                <input type="hidden" name ="next" next="">
            </form>
        </div>
        <div class="d-flex flex-row align-items-center justify-content-center container col-sm-6 col-10 card p-3 mt-3">
            Dont have a account Resigter <a class="mx-2" href="{% url 'students:register' %}" style="text-decoration: none;" > here</a>

        </div>    
    </div>
    
</section>

{% endblock %}

students/templates/students/register.html
{% extends 'students/base.html' %}
{% block title %} Register {% endblock %}
{% block nav %} Login {% endblock %}
{% block content %} 

{% load crispy_forms_tags %}

<div class="container col-sm-8 " style="margin-top: 6rem;height:70vh;margin-bottom:2rem;">
    <form action="/students/register" method="POST" >
        {% csrf_token %}
       {{form | crispy}}
       <button type="submit" class="btn btn-success mt-3">Register</button>
    </form>
</div>

{% endblock %}

students/templates/students/student.html
{% extends 'students/base.html' %}
{% block content %} 
<style>
  button{
    border: none;
    text-decoration: none;
    background-color: white;
    color: rgb(97, 97, 97);
  }
  button:active{
    color: rgb(35, 35, 35);
  }
</style>

<div class="container-fluid" style="margin-top: 5rem; margin-bottom:1rem;">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">
                <span data-feather="home"></span>
                Dashboard
              </a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file"></span>
                Orders
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="shopping-cart"></span>
                Products
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="users"></span>
                Customers
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="bar-chart-2"></span>
                Reports
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="layers"></span>
                Integrations
              </a>
            </li> -->
          </ul>
  
          <!-- <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Saved reports</span>
            <a class="link-secondary" href="#" aria-label="Add a new report">
              <span data-feather="plus-circle"></span>
            </a>
          </h6>
          <ul class="nav flex-column mb-2">
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file-text"></span>
                Current month
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file-text"></span>
                Last quarter
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file-text"></span>
                Social engagement
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file-text"></span>
                Year-end sale
              </a>
            </li>
          </ul> -->
        </div>
      </nav>
  
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Dashboard</h1>
          <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
              <!-- <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
              <button type="button" class="btn btn-sm btn-outline-secondary">Export</button> -->
              <h6 class="text-success">{{user.username}}</h6>
            </div>
            <!-- <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
              <span data-feather="calendar"></span>
              This week
            </button> -->
          </div>
        </div>
  
        <section class="my-4 w-100" id="myChart" width="900" height="380">
            <div class="container d-flex justify-content-around " style="border-bottom: 1px solid rgb(235, 235, 235); margin-bottom:2rem;">
                <button class="switch " href="" data-page="page1">Borrowed</button>
                <button class="switch " href="" data-page="page2">Requested</button>
            </div>
            <div class="bulb" id="page1" style="display: none;" >
              <h5>Borrowed</h5>
              <ul>
                {% for borrow in borrowed %}
                {% if borrow.issued == True and borrow.returned == False %}
                <li>{{borrow.book}}</li>
                {% endif %}
                {% endfor %}

              </ul>
            </div>
            <div class="bulb" id="page2" style="display: none;">
              <h5>Requested</h5>
              <ul>
                {% for borrow in borrowed %}
                {% if borrow.issued == False %}
                <li>{{borrow.book}}</li>
                {% endif %}
                {% endfor %}

              </ul>
            </div>
        </section>
     
        <!-- <h2>Section title</h2>
        <div class="table-responsive">
          <table class="table table-striped table-sm">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Header</th>
                <th scope="col">Header</th>
                <th scope="col">Header</th>
                <th scope="col">Header</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1,001</td>
                <td>random</td>
                <td>data</td>
                <td>placeholder</td>
                <td>text</td>
              </tr>
              <tr>
                <td>1,002</td>
                <td>placeholder</td>
                <td>irrelevant</td>
                <td>visual</td>
                <td>layout</td>
              </tr>
              <tr>
                <td>1,003</td>
                <td>data</td>
                <td>rich</td>
                <td>dashboard</td>
                <td>tabular</td>
              </tr>
              <tr>
                <td>1,003</td>
                <td>information</td>
                <td>placeholder</td>
                <td>illustrative</td>
                <td>data</td>
              </tr>
              <tr>
                <td>1,004</td>
                <td>text</td>
                <td>random</td>
                <td>layout</td>
                <td>dashboard</td>
              </tr>
              <tr>
                <td>1,005</td>
                <td>dashboard</td>
                <td>irrelevant</td>
                <td>text</td>
                <td>placeholder</td>
              </tr>
              <tr>
                <td>1,006</td>
                <td>dashboard</td>
                <td>illustrative</td>
                <td>rich</td>
                <td>data</td>
              </tr>
              <tr>
                <td>1,007</td>
                <td>placeholder</td>
                <td>tabular</td>
                <td>information</td>
                <td>irrelevant</td>
              </tr>
              <tr>
                <td>1,008</td>
                <td>random</td>
                <td>data</td>
                <td>placeholder</td>
                <td>text</td>
              </tr>
              <tr>
                <td>1,009</td>
                <td>placeholder</td>
                <td>irrelevant</td>
                <td>visual</td>
                <td>layout</td>
              </tr>
              <tr>
                <td>1,010</td>
                <td>data</td>
                <td>rich</td>
                <td>dashboard</td>
                <td>tabular</td>
              </tr>
              <tr>
                <td>1,011</td>
                <td>information</td>
                <td>placeholder</td>
                <td>illustrative</td>
                <td>data</td>
              </tr>
              <tr>
                <td>1,012</td>
                <td>text</td>
                <td>placeholder</td>
                <td>layout</td>
                <td>dashboard</td>
              </tr>
              <tr>
                <td>1,013</td>
                <td>dashboard</td>
                <td>irrelevant</td>
                <td>text</td>
                <td>visual</td>
              </tr>
              <tr>
                <td>1,014</td>
                <td>dashboard</td>
                <td>illustrative</td>
                <td>rich</td>
                <td>data</td>
              </tr>
              <tr>
                <td>1,015</td>
                <td>random</td>
                <td>tabular</td>
                <td>information</td>
                <td>text</td>
              </tr>
            </tbody>
          </table>
        </div> -->
        
      </main>
    </div>
  </div>
  
  <script>
    
    function showPage(page) {
        document.querySelectorAll('.bulb').forEach(div => {
            div.style.display = 'none'
        })
        document.querySelector(`#${page}`).style.display = 'block'
    }

    document.addEventListener('DOMContentLoaded', function() {
        document.querySelectorAll('.switch').forEach(button  => {
            button.onclick = function(){
                showPage(this.dataset.page); //this refers to the current button on loop
            }
        })
    })
  </script>

{% endblock %}