books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    path('',views.home,name="home"),
    path('debug/',views.debug,name="debug"),
    path('borrow/<int:book_id>',views.borrow,name="borrow"),
    path('sections/',views.sections,name="sections"),
    path('sections/sect/<int:dept>',views.sect,name="sect"),
    path('token/<int:book_id>',views.token,name='token')
    
]

main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static

from django.views.static import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('students/',include('students.urls')),
    path('',include("django.contrib.auth.urls")),
    
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]


if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.contrib.auth import views as v
from django.urls import path,include
from . import views

app_name = 'students'
urlpatterns = [
    # path('',include("django.contrib.auth.urls")),
    path('register',views.register,name='register'),
    path('login/',views.studentlogin,name="login"),
    path('student',views.student,name="student")
]

books/models.py
from distutils.command.upload import upload
from django.db import models
from django.utils import timezone
import datetime
# from .models import Borrow
from students.models import Department,Student

# Create your models here.
class Author(models.Model):
    name=models.CharField(max_length=350)
    description=models.CharField(max_length=450)
    def __str__(self):
        return self.name
    
class Book(models.Model):
    name=models.CharField(max_length=350)
    author=models.ForeignKey(Author,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="images/",default="images/default.png")
    department=models.ForeignKey(Department,on_delete=models.SET_NULL,null=True)
    issued=models.BooleanField(default=False)
    
    def __str__(self):
        return self.name  
    
class Borrow(models.Model):
    student=models.ForeignKey(Student,on_delete=models.CASCADE,null=True)
    token=models.CharField(max_length=10,null=True)
    book=models.ForeignKey(Book,on_delete=models.CASCADE)
    created_at=models.DateTimeField( auto_now=True)
    issued=models.BooleanField(default=False)
    issued_at=models.DateTimeField( auto_now=False,null=True,blank=True)
    returned=models.BooleanField(default=False)
    return_date=models.DateTimeField(auto_now=False,auto_created=False,auto_now_add=False,null=True,blank=True)
    
    def __str__(self):
        return f"Borrow Request {self.student} - {self.book} - {self.token} "
        # return "{} - {} book Borrow request".format(self.student,self.book)
    



    def days(self):
        "Returns the no. of days before returning / after return_date."
        if self.issued:
            y,m,d=str(timezone.now().date()).split('-')
            today=datetime.date(int(y),int(m),int(d))
            
            y2,m2,d2=str(self.return_date.date()).split('-')
            lastdate=datetime.date(int(y2),int(m2),int(d2))
            
            print(lastdate-today,lastdate>today)
            if lastdate > today:
                return "{} left".format(str(lastdate-today).split(',')[0])
            else:
                return "{} passed".format(str(today-lastdate).split(',')[0])
        else:
            return ""

books/views.py
from django import db
from django.shortcuts import render
from requests import request
import random

from students.models import Department, Student
from .models import Book,Author, Borrow
from django.contrib.auth.decorators import login_required

# Create your views here.
# @login_required
def home(request):
    current_user = request.user
    context ={"user":current_user}
    
    if "usersearch" in request.GET:
        query = request.GET['usersearch']
        u = Book.objects.filter(name__startswith=query).all()
        context['query'] = u
        context['item'] = query
        
    return render(request,'books/home.html', context)

def debug(request):
     #debug start
    booksfromdb = Book.objects.all()
    context = {'books': booksfromdb}
    #debug end
    return render(request,'books/debug.html', context)
@login_required
def borrow(request,book_id):
    book = Book.objects.get(id=book_id)
    context = {'book' : book}
    return render(request,'books/borrow.html',context)


@login_required
def token(request,book_id):
    req_book = Book.objects.get(id=book_id)
    current_user = request.user
    student = Student.objects.get(student_id=current_user)
    
    token = ''
    if request.method == 'POST':
        if req_book.issued == False:
            seq = (1,2,3,4,5,6,7,8,9,0)
            tk = random.sample(seq,5)
            token = int(''.join(str(e) for e in tk))
            print(student)
            
            borrow_req = Borrow(book=req_book,student=student,token=token)
            borrow_req.save()
        return render(request,'books/token.html',{'token':token})
        # return render(request,'books/token.html', )

def sections(request):
    
    # sections = ['Commerce','English','Tamil','History','Political Science','Mathematics','Economic',
    #             'statistics','Public Administration','Social Work','Chemistry','Physics','Botony','Zoology','Physical Education']
    # sfs = ['Journalism','Computer Application','Computer Science','Visual Communication','Psycology']
    
    # lib_sec = ['Reference','Commerce','Visual Communication','Tamil','English','Mathematic','History','Chemistry','Botony',
    #            'Zoology','Economics','Computer Application','Computer Science','Public Administration','Social Work']
    icons = ['fa-solid fa-briefcase','fa-solid fa-clapperboard','fa-solid fa-gopuram','fa-solid fa-archway','fa-solid fa-divide','fa-solid fa-landmark-dome','fa-solid fa-flask','fa-solid fa-seedling','fa-solid fa-frog','fa-solid fa-globe','fa-solid fa-desktop','fa-solid fa-chart-pie','fa-solid fa-users']
    books = Book.objects.all()
    lib_sec = Department.objects.all()
    context = {"sections": lib_sec,"books":books,"icons":icons}
    return render(request,'books/sections.html', context)


def sect(request,dept):
    depart = Department.objects.get(id=dept)
    print(depart.id)
    books = Book.objects.filter(department=depart.id)
    # borrow_list = Borrow.objects.all()
    return render(request,'books/sect.html', {"dept":depart,"books":books,})

books/templates/books/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap cdn link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- font awsome cdn link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- sfpro font cdn link -->
    <link href="http://fonts.cdnfonts.com/css/sf-pro-display" rel="stylesheet">
    <title>{% block title%} {% endblock %}</title>

    <style>
        *{
            font-family: 'SF Pro Display';
        }
        .cursor-p{
            cursor: pointer;
        }
        a{
            text-decoration: none;
        }
        .bg-neutral{
            background: #FBFBFD;
        }
        .bg-main{
            background:#1C1B3B ;
        }
        .bg-cta{
            background:#78091E ;
        }
        .fs-small{
            font-size: 14px;
        }
        .apple-bg{
            background: #F5F5F7;
        }
        .apple-fg{
            background: #FFFFFF;
        }
        .text-black{
            color: #1D1D1F;
        }

    </style>
</head>
<body class="apple-bg">

    <!-- navbar section -->
    <nav class="navbar navbar-expand-md bg-main navbar-dark py-3 fixed-top">
        <div class="container">
            <a href="/" class="navbar-brand"> Miller Memorial Library </a>
            <button 
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navmenu"
            >
                <span class="navbar-toggler-icon"></span>
        </button>

            <div class="collapse navbar-collapse" id="navmenu"">
                <ul class="navbar-nav ms-auto fs-small text-center">
                    <li class="nav-item">
                        <a href="/" class="nav-link">Home</a>
                    </li> 
                    <li class="nav-item">
                        <a href="{% url 'books:sections' %}" class="nav-link">Sections</a>
                    </li>
                    <li class="nav-item">
                        <a href="https://drive.google.com/drive/folders/0B3bpNsc5dBEWYjh3V3RGM00xNjA?resourcekey=0-vL_Rkim-1SegAaH2Qlu1yg" target="_blank" class="nav-link">Question Papers</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'students:student' %}" class="nav-link">{{user.username}}</a>
                    <li class="nav-item">
                        <a href="/logout" class="nav-link">logout</a>
                        {% else %}
                    </li><li class="nav-item">
                        <a href="/students/login" class="nav-link">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>

        </div>
    </nav>



    {% block content %}{% endblock %}

    <footer class="text-center text-lg-start" style="bottom:0%;">
      
        <!-- Copyright -->
        <div class="text-center pt-3 text-muted" style="font-size:13px;" >
          © 2020 Copyright
          <a class="text-muted" href="https://mcc.edu.in/" target="_blank" style="text-decoration: none;">Madras Christian College</a> <p>This is not a official site. Developed for Educational Purpose only. </p>
        </div>
        <!-- Copyright -->
      </footer>
    <!-- bootstrap scripts -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
</body>
</html>

books/templates/books/borrow.html
{% extends 'books/base.html' %}
{% block title%}Borrow{% endblock %}

{% block content %}

<section class="container" style="margin-top: 6rem;">
    <div class="container">
            <div class="col-lg-4 offset-lg-4">
                <div class="card mb-3" style="max-width: 540px;border:none;">
                    <div class="row g-0">
                        <div class="col-md-6 col-sm-6 col-5">
                            <img src="{{ book.image.url }}" class="img-fluid rounded-start" alt="...">
                        </div>
                        <div class="col-sm-6 col-lg-6 col-6">
                            <div class="card-body ">
                                <h5 class="card-title">{{book.name}}</h5>
                                <p class="card-subtitle text-muted" style="font-size:13px;">by <span class="card-text">{{book.author}}</span></p>
                                <!-- <p class="card-text">This is a wider card with supporting text below as a natural</p> -->
                                                    
                                <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
                            </div>
                        </div>
                       
                    </div>
                </div>
                <form action=" {% url 'books:token' book.id %} " method="POST" class="mt-5">
                    {% csrf_token %}
                    <button class="btn text-light col-8  bg-cta">Request borrow</button>
                </form>
            </div>
        </div>
          
    </div>

</section>

{% endblock %}

books/templates/books/debug.html
{% extends 'books/base.html' %}
{% block title%}Miller Memorial Library{% endblock %}

{% block content %}
<section class="mx-3">
    <h3 class="mt-3 mx-3 mb-5">result</h3>
    <div class="container">
        <div class="row row-cols-1 row-cols-lg-3 row-cols-md-2 g-4">
            {% for book in books %}

            <div class="col-lg-4">
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-6 col-sm-6 col-5">
                            <img src="{{ book.image.url }}" class="img-fluid rounded-start" alt="...">
                        </div>
                        <div class="col-sm-6 col-lg-6 col-6">
                            <div class="card-body">
                                <h5 class="card-title">{{book.name}}</h5>
                                <p class="card-subtitle text-muted" style="font-size:13px;">by <span class="card-text">{{book.author}}</span></p>
                                <p class="card-text">This is a wider card with supporting text below as a natural</p>
                                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>
{% endblock %}

books/templates/books/home.html
{% extends 'books/base.html' %}
{% block title%}Miller Memorial Library{% endblock %}


{% block content %}

<section class="bg-main text-light p-5 pt-lg-5 text-center text-sm-start" style="margin-top: 3rem; padding-bottom:4rem;"> 
    <div class="container col-sm-6 d-sm-flex justify-content-center">
        <form action="">
            {% csrf_token %}
        <div class="input-group rounded">
        <input name="usersearch" type="search" class="form-control" placeholder="Search for book" aria-label="Search" aria-describedby="search-addon" />
        <button class="input-group-text border-0" id="search-addon" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </form>
    </div>
</section>

<section class="mx-3" style="margin-bottom:3rem ;">
    <h3 class="mt-3 mx-3 mb-5">{{item}}</h3>
    <div class="container">
        <div class="row row-cols-1 row-cols-lg-3 row-cols-md-2 g-4">
            {% if query %}
            {% for q in query %}

            <div class="col-lg-4">
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-6 col-sm-6 col-5">
                            <img src="{{ q.image.url }}" class="img-fluid rounded-start" alt="...">
                        </div>
                        <div class="col-sm-6 col-lg-6 col-6">
                            <div class="card-body">
                                <h5 class="card-title">{{q.name}}</h5>
                                <p class="card-subtitle text-muted mb-5" style="font-size:13px;">by <span class="card-text">{{q.author}}</span></p>
                                <!-- <p class="card-text">This is a wider card with supporting text below as a natural</p> -->
                                {% if q.issued == True %}
                                <a href="" class="btn btn-danger disabled mt-5">Borrowed</a>
                                {% else %}
                                <a href="{% url 'books:borrow' book_id=q.id %}" class="btn btn-success mt-5">Borrow</a>
                                {% endif %}
                                <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif%}

        </div>
    </div>
</section>
{% endblock %}

books/templates/books/sect.html
{% extends 'books/base.html' %}
{% block content %} 


<section class="container" style="margin-top: 6rem;">
   <h1>{{dept}}</h1> 

   <div class="container pt-2">
      <div class="row row-cols-1 row-cols-lg-3 row-cols-md-2 g-4">
          {% for book in books %}

          <div class="col-lg-4">
              <div class="card mb-3" style="max-width: 540px;">
                  <div class="row g-0">
                      <div class="col-md-6 col-sm-6 col-5">
                          <img src="{{ book.image.url }}" class="img-fluid rounded-start" alt="...">
                      </div>
                      <div class="col-sm-6 col-lg-6 col-6">
                          <div class="card-body">
                              <h5 class="card-title">{{book.name}}</h5>
                              <p class="card-subtitle text-muted" style="font-size:13px;">by <span class="card-text">{{book.author}}</span></p>
                              <!-- <p class="card-text">This is a wider card with supporting text below as a natural</p> -->
                              {% if book.issued == True %}
                              <a href="" class="btn btn-danger disabled mt-3">Borrowed</a>
                              {% else %}
                              <a href="{% url 'books:borrow' book_id=book.id %}" class="btn btn-success mt-5">Borrow</a>
                              {% endif %}
                              <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
                          </div>
                      </div>
                  </div>
              </div>
          </div>

          {% endfor %}

      </div>
  </div>
</section>
{% endblock %}

books/templates/books/sections.html
{% extends 'books/base.html' %}
{% block title %} Section {% endblock %}

{% block content %} 

<section class="container col-sm-6" style="margin-top:6rem ;">
    <h2 class="mx-3">Sections</h2>
    <div class="container text-left d-text-center flex justify-content-center">
        
        {% for sec in sections %}

        <div class="container col-sm--6 col-12 card cursor-p p-3 my-1 d-flex flex-row align-items-center" style="border: none;">     
            <i class="{{sec.icons}}"></i>
            <a class="text-black mx-2" href="{% url 'books:sect' sec.id %}">{{sec}}</a>
        </div>
        {% endfor %}
        
    </div>

</section>

{% endblock %}

books/templates/books/token.html
{% extends 'books/base.html' %}
{% block content %} 

<section class="container" style="margin-top: 8rem;">

    
<div class="container col-lg-6 offset-lg-3 d-flex flex-column align-items-center">   
    <h3 class="">Your Request has been submitted</h3>
    <div>Provide this borrow request Pin at checkout</div>
    <div class="p-2 fs-4">{{token}}</div>
</div>

</section>

{% endblock %}